spring:
 profiles: "dev"
 datasource:
  driverClassName: 'oracle.jdbc.driver.OracleDriver'
  username: onair
  password: nbcci
  url: jdbc:oracle:thin:@//aoadbsq00002c0.tfayd.com:15193/U124rpt
  

  boot:
    admin:
      password: admin123
      username: admin
      url:
      - http://admin-server.labash.inbcu.com
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
  
product:
 owner: Adsales Dev

---
 
spring:
 profiles: "stage"
 datasource:
  driverClassName: 'oracle.jdbc.driver.OracleDriver'
  username: onair
  password: nbcci
  url: jdbc:oracle:thin:@//aoadbsq00002c0.tfayd.com:15193/U124rpt
  
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true  

product:
 owner: Adsales Stage
