spring:
 profiles: "dev"
 datasource:
  driverClassName: 'oracle.jdbc.driver.OracleDriver'
  username: onair
  password: nbcci
  url: jdbc:oracle:thin:@//aoadbsq00002c0.tfayd.com:15193/U124rpt

product:
 owner: Adsales Dev
  
---
 
spring:
 profiles: "stage"
 datasource:
  driverClassName: 'oracle.jdbc.driver.OracleDriver'
  username: onair
  password: nbcci
  url: jdbc:oracle:thin:@//aoadbsq00002c0.tfayd.com:15193/U124rpt

product:
 owner: Adsales Stage
